<?php
return [
    'bio' => 'Bergerak untuk Perubahan yang Lebih Baik, Inovatif dan Visioner!',
    'Title' => 'Sejarah Politeknik Piksi Ganesha',
    'paragraph1' => 'Keberadaan Politeknik Piksi Ganesha Indonesia berawal dari visi tokoh-tokoh Yayasan Bhineka Karya yang berdiri pada tanggal 17 Mei 2002 di Karanganyar dengan SK Menteri Pendidikan Nasional No. 99/D/O/2002. Saat itu berdirilah sebuah lembaga pendidikan tinggi bernama Politeknik Dharma Patria Kebumen yang memanfaatkan gedung SMK Bhina ​​Karya 2 Karanganyar yang berada di bawah yayasan yang sama dengan Bhineka Karya. Politeknik Dharma Patria Kebumen pada awalnya menawarkan empat program studi, yaitu Akuntansi, Teknik Elektronika, Teknik Mesin, dan Teknik Otomotif.',
    'paragraph2' => 'Jumlah mahasiswa Politeknik Dharma Patria Kebumen terus meningkat dari tahun ke tahun. Namun pada tahun 2011, timbul konflik di antara pengurus yayasan sehingga Politeknik Dharma Patria Kebumen diakuisisi oleh Politeknik Piksi Ganesha Bandung. Kampus dipindahkan ke pusat kota Kebumen, di Jalan Jenderal Ahmad Yani No.1, Kebumen.',
    'paragraph3' => 'Pada bulan April 2011, lembaga ini mulai menerima mahasiswa baru. Di bawah manajemen baru dan didukung oleh berbagai upaya promosi, jumlah calon mahasiswa meningkat signifikan dibandingkan dengan manajemen sebelumnya. Masyarakat, khususnya lulusan SMA, sangat antusias untuk mendaftar di Politeknik Dharma Patria Kebumen. Menariknya, tidak hanya lulusan baru, pejabat pemerintah daerah, seperti kepala desa, sekretaris desa, dan guru yang hanya berpendidikan SMA, juga berminat untuk mendaftar.',
    'paragraph4' => 'Sebagai bentuk komitmennya, pada tanggal 14 November 2012, lembaga ini meresmikan Gedung Rektorat Politeknik Dharma Patria Kebumen yang beralamat di Jalan Letjend Suprapto No. 73, Kebumen (sebelah Koramil Kebumen). Usai peresmian, lembaga ini langsung menerima asesor dari BAN-PT (Badan Akreditasi Nasional Perguruan Tinggi) untuk melakukan visitasi akreditasi selama 10 hari.',
    'paragraph5' => 'Pada tanggal 16 Oktober 2021, Politeknik Dharma Patria resmi berganti nama menjadi Politeknik Piksi Ganesha Indonesia. Penyerahan sertifikat perubahan nama dilakukan oleh Ketua Yayasan Piksi Ganesha Indonesia, Dr. K.H. Prihartono, A.H., Drs., S.Sos., M.Kom., M.M, kepada Direktur Politeknik Piksi Ganesha.', 
];
