<?php
return [
    'bio' => 'Moving for Better, Innovative and Visionary Change!',
    'Title' => 'History of International Students',
    'paragraph1' => 'The existence of Politeknik Piksi Ganesha Indonesia originated from the vision of the key figures of the Bhineka Karya Foundation, which was established on May 17, 2002, in Karanganyar with the decree of the Minister of National Education No. 99/D/O/2002. At that time, a higher education institution called Politeknik Dharma Patria Kebumen was founded, 
            utilizing the building of SMK Bhina Karya 2 Karanganyar, which was under the same foundation as Bhineka Karya. Politeknik Dharma Patria Kebumen initially offered four programs of study: Accounting, Electronics Engineering, Mechanical Engineering, and Automotive Engineering.',
    'paragraph2' => 'The number of students at Politeknik Dharma Patria Kebumen steadily increased year by year. However, in 2011, a conflict arose among the foundation s management, leading to the acquisition of Politeknik Dharma Patria Kebumen by Politeknik Piksi Ganesha Bandung. The campus was relocated to the center of Kebumen city, at Jalan Jenderal Ahmad Yani No. 1, Kebumen.',
    'paragraph3' => 'In April 2011, the institution began accepting new student enrollments. Under the new management and supported by promotional efforts, there was a significant increase in the number of prospective students compared to the previous management. The public, particularly recent high school graduates, showed great enthusiasm in registering for Politeknik Dharma Patria Kebumen. 
                     Interestingly, not only fresh graduates but also local government officials, such as village heads, village secretaries, and teachers with only a high school education, were interested in enrolling.',
    'paragraph4' => 'To demonstrate its commitment, on November 14, 2012, the institution inaugurated the Politeknik Dharma Patria Kebumen Rectorate Building, located at Jalan Letjend Suprapto No. 73, Kebumen (next to the Koramil Kebumen). Following the inauguration, the institution immediately received assessors from BAN-PT (National Accreditation Board for Higher Education) for an accreditation visit lasting 10 days.',
    'paragraph5' => 'On October 16, 2021, Politeknik Dharma Patria officially changed its name to Politeknik Piksi Ganesha Indonesia. The handover of the name change certificate was carried out by the Chairman of the Piksi Ganesha Indonesia Foundation, Dr. K.H. Prihartono, A.H., Drs., S.Sos., M.Kom., M.M, to the Director of Politeknik Piksi Ganesha.',        
];
